backend:
  name: github
  repo: ndnk0311/de_tai_nhom_10_n 
  branch: main
  auth_endpoint: 'https://api.github.com'
  client_id: 'Ov23li2cJXvWLYwaL7eS'         
  client_secret: '46f158af885b3558d72732c488d4d960fff61aaf' 
  base_url: 'https://github.com/login/oauth/authorize'
  auth_scope: 'repo'

media_folder: 'assets/uploads'
public_folder: '/uploads'

collections:
  - name: 'about'
    label: 'Giới Thiệu'
    folder: 'content/about'
    create: true
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'

  - name: 'attractions'
    label: 'Địa Điểm Tham Quan'
    folder: 'content/attractions'
    create: true
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Description'
        name: 'description'
        widget: 'text'
      - label: 'Image'
        name: 'image'
        widget: 'image'
        required: true

  - name: 'gallery'
    label: 'Thư Viện Ảnh'
    folder: 'content/gallery'
    create: true
    fields:
      - label: 'Images'
        name: 'images'
        widget: 'list'
        fields:
          - label: 'Image'
            name: 'image'
            widget: 'image'
            required: true

  - name: 'contact'
    label: 'Liên Hệ'
    folder: 'content/contact'
    create: true
    fields:
      - label: 'Email'
        name: 'email'
        widget: 'string'
      - label: 'Address'
        name: 'address'
        widget: 'string'
